version: "3"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./mongoData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Example
    ports:
      - 27017:27017
