version: "3"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Example
    ports:
      - 27272:27017

volumes:
  mongoData:
    driver: local
