export const EXAMPLES_LOADING = "EXAMPLES_LOADING";
export const EXAMPLES_LOADED = "EXAMPLES_LOADED";
export const ADD_EXAMPLE = "ADD_EXAMPLE";
export const DELETE_EXAMPLE = "DELETE_EXAMPLE";
export const CLEAR_EXAMPLES = "CLEAR_EXAMPLES";
